advarisk_news_articles_app/advarisk_news_articles_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("app_users/", include("app_user.urls")),
    path("articles/", include("articles.urls")),
    path("admin/", admin.site.urls),
]

advarisk_news_articles_app/app_user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

advarisk_news_articles_app/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.home, name='home'),
]

advarisk_news_articles_app/app_user/models.py
from django.db import models


class AppUsers(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)

advarisk_news_articles_app/articles/models.py
from django.db import models
from app_user.models import AppUsers

class ArticleUsers(models.Model):
    search_data = models.CharField(max_length=200)
    search_user_id = models.ForeignKey(AppUsers, on_delete=models.CASCADE)

advarisk_news_articles_app/app_user/views.py
from django.http import HttpResponse
from django.shortcuts import render
from app_user.models import AppUsers
from app_user.serializer import AppUserSerializer
from django.shortcuts import render
import requests
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from rest_framework import status

from rest_framework.decorators import api_view
# Create your views here.


def index(request):
    return render(request, "select_user.html")

#def home(request):
    #context1 = {'users' : AppUsers.objects.filter(is_active=True)}
    #r = requests.get('https://newsapi.org/v2/everything?q=tesla&from=2023-09-01&sortBy=publishedAt&apiKey=2e6fbc71fbeb488896e0198a9dfa0a49', params=request.GET)
    #data = r.json()
    #print(data['articles'][0])
    #return render(request, 'home_page.html', context1)

advarisk_news_articles_app/articles/views.py
from django.shortcuts import render
from app_user.models import AppUsers
from articles.models import ArticleUsers
from app_user.serializer import AppUserSerializer
from articles.serializer import ArticleSerializer
from django.shortcuts import render
import requests
from datetime import date, timedelta



from rest_framework.decorators import api_view
# Create your views here.

def home(request):
    defalut_text = 'tesla'
    user_id = None
    if request.method == 'POST':
        user_email=request.POST.get('user_email')
        user_search_text=request.POST.get('user_search_text')
        form_user_id=request.POST.get('form_user_id')
        if user_search_text == None:
            try:
                app_user = AppUsers.objects.get(email=user_email)
                user_id = app_user.id
            except AppUsers.DoesNotExist:
                name = user_email.split("@")
                user_data = {"name":name[0], "email":user_email}
                app_user_serializer = AppUserSerializer(data=user_data)
                if app_user_serializer.is_valid():
                    app_user = app_user_serializer.save()
                    user_id = app_user.id
                    #print(app_user.id)
        else:
            defalut_text = user_search_text
    today = date.today() - timedelta(days=30)
    r = requests.get('https://newsapi.org/v2/everything?q='+str(defalut_text)+'&from=2023-09-02&sortBy=publishedAt&apiKey=2e6fbc71fbeb488896e0198a9dfa0a49', params=request.GET)
    articles = []
    try:
        data = r.json()
        articles = data['articles']
    except:
        pass
    if not user_id == None:
        user_data = {"search_data":defalut_text, "search_user_id":user_id}
        article_user_serializer = ArticleSerializer(data=user_data)
        if article_user_serializer.is_valid():
            article_user = article_user_serializer.save()
            user_id = article_user.id
    context1 = {'articles' : articles, "user_id": user_id}
    return render(request, 'home_page.html', context1)

advarisk_news_articles_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} <title>JI Assignment</title> {% endblock title %}
</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

advarisk_news_articles_app/templates/home_page.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div>
	<div class="card-body">
		<h3>Articles</h3>
		<form action="{% url 'articles:home' %}" method="post">
			{% csrf_token %}
			<fieldset>
				<legend><input type="text" name="user_search_text" id="user_search_text", placeholder="Enter text to search...!" value=""></legend>
			</fieldset>
			<input type="hidden" name="form_user_id" id="form_user_id", value="{{ user_id }}">
			<input type="submit" value="Submit">
		</form>
        <table class="table table-striped table-borderless" style="border: 1px solid black;">
		  <thead>
			<tr>
			  <th scope="col">#</th>
			  <th scope="col">Author</th>
			  <th scope="col">Title</th>
			  <th scope="col">date</th>
			  <th scope="col">URL</th>
			</tr>
		  </thead>
		  <tbody style="border: 1px solid black;">
            {% for article in articles %}

			<tr>
			  <th scope="row">{{ forloop.counter }}</th>
			  <td>{{ article.author }}</td>
			  <td>{{ article.title }}</td>
              <td>{{ article.publishedAt }}</td>
              <td><a href="{{ article.url }}" target="_blank">news url</a></td>
			</tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>
{% endblock content %}

<form action="{% url 'articles:home' %}" method="post">
	{% csrf_token %}
	<div style="width: 50%;margin: auto;">
		<div class="card-body">
			<h3>Find new feeds...!</h3>
			<table class="table table-striped table-borderless" style="border: 1px solid black;">
			  <tbody style="border: 1px solid black;">
				<tr>
				  <td><input type="text" name="user_email" id="user_email", placeholder="Enter your email...!" value=""></td>
				</tr>
			  </tbody>
			</table>
			<input type="submit" value="Submit">
		</div>
	</div>
	</form>

advarisk_news_articles_app/templates/select_user.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<form action="{% url 'articles:home' %}" method="post">
{% csrf_token %}
<div style="width: 50%;margin: auto;">
	<div class="card-body">
		<h3>Find new feeds...!</h3>
        <table class="table table-striped table-borderless" style="border: 1px solid black;">
		  <tbody style="border: 1px solid black;">
			<tr>
			  <td><input type="text" name="user_email" id="user_email", placeholder="Enter your email...!" value=""></td>
			</tr>
          </tbody>
        </table>
        <input type="submit" value="Submit">
    </div>
</div>
</form>